[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd website && npm ci"]

[phases.build]
cmds = ["cd website && npm run build:railway && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public"]

[start]
cmd = "cd website/.next/standalone && node server.js"
