[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
